title: NSG KnowledgeDB
description: The GOTO place for bioinformatics, IT and protocols in the lab
theme: just-the-docs

url: https://aharon-weizmann.github.io/KnowledgeDB

logo: "./assets/images/lab_logo.svg"
favicon_ico: "./assets/images/favicon.ico"

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.3.0"

aux_links:
  Repository: https://github.com/aharon-weizmann/KnowledgeDB
  Box: https://weizmann.box.com

aux_links_new_tab: true
