title: NSG KnowledgeDB
description: The GOTO place for bioinformatics, IT and protocols in the lab
theme: just-the-docs

url: https://aharon-weizmann.github.io/KnowledgeDB

aux_links:
  Template Repository: https://github.com/aharon-weizmann/KnowledgeDB
